services:
  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - "4151:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
  