name: ''

permissions: write-all

on:
  push:
    branches: 
      - "*" # Push events to all branches

jobs:
  build:
    runs-on: macos-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        working-directory: ./api/src

    steps:
    # Checkout the repository to the GitHub Actions runner
    - uses: actions/checkout@v2
    - name: Setup Go ${{ matrix.go-version }}
      uses: actions/setup-go@v4
      with:
        go-version: 1.21.0
    
    - name: Run make
      run: |
        make all

    - name: Run Server
      run: |
        ../darwin_x86_64/bin/apiserver & disown

    - name: Test
      run: |
        sh ../tests/minimal.sh



