name: 'Make Go Executables'

on:
  # workflow_dispatch:
  # push:
  #   branches: [ "dev", "prod" ]
  pull_request:
    branches: [ "dev", "prod" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        working-directory: ./api/src

    steps:
    # Checkout the repository to the GitHub Actions runner
    - uses: actions/checkout@v4
    - name: Setup Go ${{ matrix.go-version }}
      uses: actions/setup-go@v4
      with:
        go-version: 1.21.0
    
    - name: Updating and upgrading brew 
      run: |
        ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
        brew --version
          
    - name: Install dependencies
      run: |
        brew install FiloSottile/musl-cross/musl-cross

    - name: Run make
      run: |
        make all

    - name: Test
      run: |
        sh ./tests/minimal.sh

    - name: Create Release Package
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false


