name: 'Make Go Executables'

permissions: write-all

on:
  # workflow_dispatch:
  # push:
  #   branches: [ "dev", "prod" ]
  pull_request:
    branches: [ "dev", "prod" ]


jobs:
  build:
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        working-directory: ./api/src

    steps:
    # Checkout the repository to the GitHub Actions runner
    - uses: actions/checkout@v2
    - name: Setup Go ${{ matrix.go-version }}
      uses: actions/setup-go@v4
      with:
        go-version: 1.21.0
    
    - name: Run make
      run: |
        make all

    - name: Run Server
      run: |
        ../linux_x86_64/bin/apiserver & disown

    - name: Test
      run: |
        sh ../tests/minimal.sh

    - name: Get previous tag
      id: previoustag
      uses: 'WyriHaximus/github-action-get-previous-tag@v1'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Get next minor version
      id: semver
      uses: 'WyriHaximus/github-action-next-semvers@v1'
      with:
        version: ${{ steps.previoustag.outputs.tag }}

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ steps.semver.outputs.patch }}
        release_name: Release ${{ steps.semver.outputs.patch }}


