name: ''

permissions: write-all

on:
  push:
    branches: 
      - "*" # Push events to all branches

jobs:
  build:
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    steps:
    # Checkout the repository to the GitHub Actions runner
    - uses: actions/checkout@v2
    - name: Setup Go ${{ matrix.go-version }}
      uses: actions/setup-go@v4
      with:
        go-version: 1.21.0
    - uses: awalsh128/cache-apt-pkgs-action@v1
      with:
        packages: musl-tools # provides musl-gcc
        version: 1.0

    - name: Run make
      run: |
        cd ./api/src && make .linux

    - name: Run Server
      run: |
        ../linux_x86_64/bin/apiserver & disown

    - name: Download docker
      run: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sh get-docker.sh
    
    - name: Run docker-compose
      run: |
        cd ./message-broker/nsq && docker-compose up
        docker logs nsq-nsq_to_http-1



